# Datasource configuration for PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.default.jdbc.url=jdbc:postgresql://localhost:5432/your_database_name
quarkus.datasource.default.username=your_username
quarkus.datasource.default.password=your_password
quarkus.datasource.default.jdbc.driver=org.postgresql.Driver
quarkus.hibernate-orm.database.generation=update